import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/components/providers/ThemeProvider';
import Logo from '@/components/Logo';
import ThemeSwitcher from '@/components/ThemeSwitcher';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          disableTransitionOnChange
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <div className="">
            <nav className="flex items-center justify-between border-b border-border h-[60px] px-4 py-2">
              <Logo />
              <div className="flex gap-4 items-center">
                <ThemeSwitcher />
              </div>
            </nav>
          </div>
          <div className="mx-4 ">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
